version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - medcord-db:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  medcord-backend:
    container_name: medcord-backend
    image: medcord_backend
    links:
      - postgres
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 5000:5000
      - 9229:9229
      - 8080:8080
    restart: unless-stopped

volumes:
    medcord-db:
        name: medcord-db