version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=mauricio
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql
    expose:
      - "5432"
    networks:
      - ensolvers-challenge-network

  backend:
      container_name: backend
      build:
        context: .
        target: development
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 5000:5000
        - 9229:9229
        - 8080:8080
      command: npm run start:dev
      networks:
        - ensolvers-challenge-network
      depends_on:
        - database

volumes:
  postgres_data:
    external: true

networks:
  ensolvers-challenge-network:
    driver: bridge
